version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - be-network
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  redis_data:

networks:
  be-network:
    external: true
